/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.mongodb.view;

import com.mongodb.BasicDBObject;
import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.DBCursor;
import com.mongodb.Mongo;
import java.net.UnknownHostException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex Velastegui ESPE-DCCO
 */
public class frmFactura extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    DB db;
    DBCollection tabla;

    public frmFactura() {
        try {
            Mongo mongo = new Mongo("localHost", 27017);
            db = mongo.getDB("Basededatos");
            tabla = db.getCollection("tabla");
        } catch (UnknownHostException ex) {

        }
        initComponents();

        tblBill.setModel(model);
        String titu[] = {"Product", "Price", "Quantity", "Total"};
        model.setColumnIdentifiers(titu);
        tblBill.getColumnModel().getColumn(0).setPreferredWidth(200);

    }

    public void validateFields() {
        if (txtCustomer.getText().isEmpty()) {
            lblCustomer.setText("*Obligatory!");
        } else {
            lblCustomer.setText("");
        }
        if (txtRUC.getText().isEmpty()) {
            lblRUC.setText("*Obligatory!");
        } else {
            lblRUC.setText("");
        }
    }

    public void enableButton() {
        if (txtCustomer.getText().isEmpty() || txtRUC.getText().isEmpty()) {
            btnSave.setEnabled(false);
        } else {
            btnSave.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMongo = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaTabla = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        pnlOrder = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCustomer = new javax.swing.JTextField();
        txtRUC = new javax.swing.JTextField();
        cmbProduct = new javax.swing.JComboBox<>();
        txtPrice = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtQuantity = new javax.swing.JTextField();
        lblRUC = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        pnlBill = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBill = new javax.swing.JTable();
        pnlTotal = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        pnlSave = new javax.swing.JPanel();
        btnSaveAll = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(960, 960));
        setMinimumSize(new java.awt.Dimension(950, 950));
        getContentPane().setLayout(null);

        pnlMongo.setBackground(new java.awt.Color(0, 0, 0));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnShow.setText("Show");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        txaTabla.setEditable(false);
        txaTabla.setColumns(20);
        txaTabla.setRows(5);
        jScrollPane2.setViewportView(txaTabla);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout pnlMongoLayout = new javax.swing.GroupLayout(pnlMongo);
        pnlMongo.setLayout(pnlMongoLayout);
        pnlMongoLayout.setHorizontalGroup(
            pnlMongoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMongoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMongoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addGroup(pnlMongoLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlMongoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMongoLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnSave)
                                .addGap(119, 119, 119)
                                .addComponent(btnShow))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)))
                .addGap(27, 27, 27))
        );
        pnlMongoLayout.setVerticalGroup(
            pnlMongoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMongoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlMongoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlMongoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlMongoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnShow))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMongo);
        pnlMongo.setBounds(480, 50, 430, 350);

        pnlOrder.setBackground(new java.awt.Color(0, 0, 0));
        pnlOrder.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer: ");
        pnlOrder.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 36, -1, -1));

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RUC :");
        pnlOrder.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 79, -1, -1));

        jLabel3.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product:");
        pnlOrder.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 124, -1, -1));

        jLabel4.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Price:");
        pnlOrder.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 171, -1, -1));

        jLabel5.setFont(new java.awt.Font("MV Boli", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantity:");
        pnlOrder.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 216, -1, -1));

        txtCustomer.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        txtCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustomerKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerKeyTyped(evt);
            }
        });
        pnlOrder.add(txtCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 36, 235, -1));

        txtRUC.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        txtRUC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRUCKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRUCKeyTyped(evt);
            }
        });
        pnlOrder.add(txtRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 79, 235, -1));

        cmbProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[Select]", "Switch", "Nortenio", "Rom Pon Pon", "Zhumir Pink", "Ron Abuelo", "Zhumir Classic", "Red Label", "Jack Daniels" }));
        cmbProduct.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbProductItemStateChanged(evt);
            }
        });
        pnlOrder.add(cmbProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 124, 233, -1));

        txtPrice.setEditable(false);
        txtPrice.setBackground(new java.awt.Color(0, 0, 0));
        txtPrice.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(255, 255, 255));
        txtPrice.setBorder(null);
        pnlOrder.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 171, 185, -1));

        btnAdd.setText("Add");
        btnAdd.setToolTipText("add beverage in the bill");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        pnlOrder.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 261, 90, -1));

        btnDelete.setText("Delete");
        btnDelete.setToolTipText("delete beverage of the bill");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlOrder.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 261, -1, -1));

        txtQuantity.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        txtQuantity.setToolTipText("choose the quantity you want");
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantityKeyTyped(evt);
            }
        });
        pnlOrder.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 216, 50, -1));

        lblRUC.setForeground(new java.awt.Color(255, 0, 0));
        pnlOrder.add(lblRUC, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 70, 30));

        lblCustomer.setForeground(new java.awt.Color(255, 0, 0));
        pnlOrder.add(lblCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 70, 30));

        getContentPane().add(pnlOrder);
        pnlOrder.setBounds(15, 46, 460, 290);

        pnlBill.setBackground(new java.awt.Color(0, 0, 0));

        tblBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product", "Price", "Quantity", "Total"
            }
        ));
        tblBill.setToolTipText("Bill");
        jScrollPane1.setViewportView(tblBill);
        if (tblBill.getColumnModel().getColumnCount() > 0) {
            tblBill.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout pnlBillLayout = new javax.swing.GroupLayout(pnlBill);
        pnlBill.setLayout(pnlBillLayout);
        pnlBillLayout.setHorizontalGroup(
            pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBillLayout.setVerticalGroup(
            pnlBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBillLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(pnlBill);
        pnlBill.setBounds(15, 389, 482, 304);

        pnlTotal.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SubTotal");

        lblSubTotal.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        lblSubTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblSubTotal.setText("00.00");

        jLabel8.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("IVA");

        lblIVA.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        lblIVA.setForeground(new java.awt.Color(255, 255, 255));
        lblIVA.setText("00.00");

        jLabel10.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("TOTAL");

        lblTotal.setFont(new java.awt.Font("MV Boli", 1, 16)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("00.00");

        javax.swing.GroupLayout pnlTotalLayout = new javax.swing.GroupLayout(pnlTotal);
        pnlTotal.setLayout(pnlTotalLayout);
        pnlTotalLayout.setHorizontalGroup(
            pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTotalLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTotalLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTotalLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlTotalLayout.setVerticalGroup(
            pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIVA)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        getContentPane().add(pnlTotal);
        pnlTotal.setBounds(240, 702, 257, 138);

        pnlSave.setBackground(new java.awt.Color(0, 0, 0));

        btnSaveAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/mongodb/icons/save.png"))); // NOI18N
        btnSaveAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAllActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/mongodb/icons/cancel.png"))); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSaveLayout = new javax.swing.GroupLayout(pnlSave);
        pnlSave.setLayout(pnlSaveLayout);
        pnlSaveLayout.setHorizontalGroup(
            pnlSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSaveLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSaveAll, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );
        pnlSaveLayout.setVerticalGroup(
            pnlSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSaveAll)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlSave);
        pnlSave.setBounds(550, 580, 173, 246);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/mongodb/icons/394134.png"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(200, 1600));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-20, -120, 1140, 1210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProductItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbProductItemStateChanged
        // TODO add your handling code here:
        String pre = "";
        if (cmbProduct.getSelectedIndex() > 0) {
            switch (cmbProduct.getSelectedIndex()) {
                case 1:
                    pre = "3.00";
                    break;
                case 2:
                    pre = "8.00";
                    break;
                case 3:
                    pre = "12.50";
                    break;
                case 4:
                    pre = "6.50";
                    break;
                case 5:
                    pre = "6.00";
                    break;
                case 6:
                    pre = "7.00";
                    break;
                case 7:
                    pre = "9.75";
                    break;
                case 8:
                    pre = "9.99";
                    break;
                default:
                    pre = "120.00";
            }
            txtPrice.setText(pre);
            txtQuantity.setText("1");
        }
    }//GEN-LAST:event_cmbProductItemStateChanged

    private double redondear(double num) {
        return Math.rint(num * 100) / 100;
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String rowData[] = new String[4];
        rowData[0] = cmbProduct.getSelectedItem().toString();
        rowData[1] = txtPrice.getText();
        rowData[2] = txtQuantity.getText();
        Double imp = Double.parseDouble(rowData[1]) * Double.parseDouble(rowData[2]);
        imp = redondear(imp);
        rowData[3] = imp.toString();
        model.addRow(rowData);
        calTot();
    }//GEN-LAST:event_btnAddActionPerformed

    private void calTot() {
        double S = 0;
        double igv;
        double tot;
        for (int i = 0; i < tblBill.getRowCount(); i++) {
            S = S + Double.parseDouble(model.getValueAt(i, 3).toString());
        }
        S = redondear(S);
        lblSubTotal.setText(String.valueOf(S));
        igv = 0.09 * S;
        igv = redondear(igv);
        tot = S * 1.09;
        tot = redondear(tot);
        lblIVA.setText(String.valueOf(igv));
        lblTotal.setText(String.valueOf(tot));

    }
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        eliminar();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        BasicDBObject document = new BasicDBObject();
        document.put("Customer", "'" + txtCustomer.getText() + "'");
        document.put("RUC", "'" + txtRUC.getText() + "'");
        tabla.insert(document);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        DBCursor cursor = tabla.find();
        while (cursor.hasNext()) {
            txaTabla.setText(txaTabla.getText() + "\n" + cursor.next());
        }
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnSaveAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAllActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Save ALL!!!");
        System.exit(0);
    }//GEN-LAST:event_btnSaveAllActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtCustomerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerKeyTyped

        char validate = evt.getKeyChar();
        if (Character.isDigit(validate)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Enter only letters");
        }
        if (evt.getKeyChar() >= 33 && evt.getKeyChar() <= 64) {
            JOptionPane.showMessageDialog(this, "Please not Special Characters!!!");
            evt.consume();
        }

    }//GEN-LAST:event_txtCustomerKeyTyped

    private void txtRUCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRUCKeyTyped

        char letter = evt.getKeyChar();
        if (Character.isLetter(letter)) {
            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(this, "Please only numbers!!!");

        }
        if (txtRUC.getText().length() >= 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRUCKeyTyped

    private void txtCustomerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerKeyReleased
        enableButton();
        validateFields();
    }//GEN-LAST:event_txtCustomerKeyReleased

    private void txtRUCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRUCKeyReleased
        enableButton();
        validateFields();
    }//GEN-LAST:event_txtRUCKeyReleased

    private void txtQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyTyped
        if (txtQuantity.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_txtQuantityKeyTyped
    private void eliminar() {
        int fil;
        if (model.getRowCount() > 0) {
            if (tblBill.getSelectedRow() != -1) {
                fil = tblBill.getSelectedRow();
                model.removeRow(fil);
                calTot();
            } else {
                JOptionPane.showMessageDialog(null, "Seleccione una Fila");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay filas en la lista");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveAll;
    private javax.swing.JButton btnShow;
    private javax.swing.JComboBox<String> cmbProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblRUC;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlBill;
    private javax.swing.JPanel pnlMongo;
    private javax.swing.JPanel pnlOrder;
    private javax.swing.JPanel pnlSave;
    private javax.swing.JPanel pnlTotal;
    private javax.swing.JTable tblBill;
    private javax.swing.JTextArea txaTabla;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtRUC;
    // End of variables declaration//GEN-END:variables
}
