/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.beverageAndOrder.view;

import ec.edu.espe.beverageAndOrder.controller.BeverageController;
import ec.edu.espe.beverageAndOrder.service.BeverageService;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Camila Venegas DCCO <your.name at your.org>
 */
public class FrmBeverage extends javax.swing.JFrame {
    private final BeverageService service;
    
    public FrmBeverage(BeverageService service) {
        initComponents();
        this.service = service;
        
        List<String> types = service.getBeverageTypes();
        types.forEach(cmbType::addItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        sprSize = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtBrand = new javax.swing.JTextField();
        txtPrice = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BEVERAGE ");
        setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/beverageAndOrder/view/2 - copia.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/beverageAndOrder/view/logo beverage.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 320, 470));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(153, 0, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(50, 4, 96));
        jLabel3.setText("Beverage Brand");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 40));

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(56, 0, 84));
        jLabel4.setText("Type ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 40));

        jPanel2.add(cmbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 250, 20));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Maiandra GD", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(80, 12, 101));
        jLabel5.setText("Size ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 90, 30));

        sprSize.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 5.0d, 0.5d));
        jPanel2.add(sprSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 100, 30));

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(78, 7, 91));
        jLabel6.setText("Price");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 60, -1));

        btnAdd.setBackground(new java.awt.Color(100, 38, 141));
        btnAdd.setFont(new java.awt.Font("Leelawadee UI", 3, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, 40));

        btnExit.setBackground(new java.awt.Color(100, 38, 141));
        btnExit.setFont(new java.awt.Font("Leelawadee UI", 3, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel2.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 110, 40));

        jPanel3.setBackground(new java.awt.Color(102, 0, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 250, -1));

        txtBrand.setBorder(null);
        jPanel2.add(txtBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 250, 30));

        txtPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jPanel2.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 100, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 300, 370));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/beverageAndOrder/view/Diseño sin título.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 380, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        float price = 0.0F;
        String brand = txtBrand.getText();
        
        if (brand.trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                null,
                "Brand is required",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            
            return;
        } else if (brand.length() < 3 || brand.length() > 20) {
            JOptionPane.showMessageDialog(
                null,
                "Brand must have between 3 and 20 characters",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            
            return;
        }
        
        try {
            price = Float.parseFloat(txtPrice.getText());
        } catch (Exception e) {}
        
        if (price == 0) {
            JOptionPane.showMessageDialog(
                null,
                "Price must be greather than zero",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        String type = (String)cmbType.getSelectedItem();
        Double size = (Double) sprSize.getValue();
        
        service.addBeverage(brand, type, price, size.floatValue());
        
        JOptionPane.showMessageDialog(
            null,
            "Product has been stored",
            "Success",
            JOptionPane.INFORMATION_MESSAGE
        );
        
        txtBrand.setText("");
        txtPrice.setText("");
        sprSize.setValue(1.0);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
       dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSpinner sprSize;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JFormattedTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
